// This file was auto-generated by ML.NET Model Builder. 

using System;
using MLWebAPIML.Model;

namespace MLWebAPIML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Id = @"19165ed7-212e-21c4-0428-030d4265475f",
                Reasonofdeath = @"Ziekte",
                Passdate = @"14/01/2021 00:00:00",
                Productiondatetime = @"01/01/2021 00:00:01",
                Date = @"01/01/2021 00:00:00",
                Feedid = 4F,
                Portion = @"9,309",
                Assigned = @"65,296",
                Consumption = @"95,168",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Production with predicted Production from sample data...\n\n");
            Console.WriteLine($"Id: {sampleData.Id}");
            Console.WriteLine($"Reasonofdeath: {sampleData.Reasonofdeath}");
            Console.WriteLine($"Passdate: {sampleData.Passdate}");
            Console.WriteLine($"Productiondatetime: {sampleData.Productiondatetime}");
            Console.WriteLine($"Date: {sampleData.Date}");
            Console.WriteLine($"Feedid: {sampleData.Feedid}");
            Console.WriteLine($"Portion: {sampleData.Portion}");
            Console.WriteLine($"Assigned: {sampleData.Assigned}");
            Console.WriteLine($"Consumption: {sampleData.Consumption}");
            Console.WriteLine($"\n\nPredicted Production: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
