// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FeedPrediction.DataModel
{
    public class ModelInput
    {
        [ColumnName("animal"), LoadColumn(0)]
        public string Animal { get; set; }


        [ColumnName("feedid"), LoadColumn(1)]
        public float Feedid { get; set; }


        [ColumnName("name"), LoadColumn(2)]
        public string Name { get; set; }


        [ColumnName("portion"), LoadColumn(3)]
        public string Portion { get; set; }


        [ColumnName("consumption"), LoadColumn(4)]
        public string Consumption { get; set; }


        [ColumnName("consumptiondate"), LoadColumn(5)]
        public string Consumptiondate { get; set; }


        [ColumnName("production"), LoadColumn(6)]
        public float Production { get; set; }


        [ColumnName("productiondate"), LoadColumn(7)]
        public string Productiondate { get; set; }


    }
}
