// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLWebAPIML.Model
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public string Id { get; set; }


        [ColumnName("reasonofdeath"), LoadColumn(1)]
        public string Reasonofdeath { get; set; }


        [ColumnName("passdate"), LoadColumn(2)]
        public string Passdate { get; set; }


        [ColumnName("production"), LoadColumn(3)]
        public float Production { get; set; }


        [ColumnName("productiondatetime"), LoadColumn(4)]
        public string Productiondatetime { get; set; }


        [ColumnName("date"), LoadColumn(5)]
        public string Date { get; set; }


        [ColumnName("feedid"), LoadColumn(6)]
        public float Feedid { get; set; }


        [ColumnName("portion"), LoadColumn(7)]
        public string Portion { get; set; }


        [ColumnName("assigned"), LoadColumn(8)]
        public string Assigned { get; set; }


        [ColumnName("consumption"), LoadColumn(9)]
        public string Consumption { get; set; }


    }
}
